### ISSUE TITLE
Impossible to install claspy package using pip

### ISSUE THREAD

**Issue by darioamorosodaragona-tuni** [ermshaua/claspy#2]
```
python -m pip install claspy
ERROR: Could not find a version that satisfies the requirement claspy (from versions: none)
ERROR: No matching distribution found for claspy

```

**Comment by ermshaua** [comment]
Which Python version do you use?

**Comment by darioamorosodaragona-tuni** [comment]
I tried: 
- Python 10: error

```
  ERROR: Command errored out with exit status 1:
   command: /Users/ncdaam/PycharmProjects/time-series-analysis/venv_mac/bin/python /Users/ncdaam/PycharmProjects/time-series-analysis/venv_mac/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/tmpncodlpkn
       cwd: /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/pip-install-32pu0gpl/claspy_83dc84bf14f64fa0bcd1c4d56a3438d1
  Complete output (36 lines):
  running dist_info
  creating /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/pip-modern-metadata-0pwf14hf/claspy.egg-info
  Traceback (most recent call last):
    File "/Users/ncdaam/PycharmProjects/time-series-analysis/venv_mac/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/Users/ncdaam/PycharmProjects/time-series-analysis/venv_mac/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/ncdaam/PycharmProjects/time-series-analysis/venv_mac/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 16, in <module>
      setup(
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/dist_info.py", line 31, in run
      egg_info.run()
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 292, in run
      writer(self, ep.name, os.path.join(self.egg_info, ep.name))
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 635, in write_pkg_info
      metadata.write_pkg_info(cmd.egg_info)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1118, in write_pkg_info
      self.write_pkg_file(pkg_info)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 182, in write_pkg_file
      license = rfc822_escape(self.get_license())
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/util.py", line 533, in rfc822_escape
      lines = header.split('\n')
  AttributeError: 'dict' object has no attribute 'split'
```
The error si the same for all the version of claspy, pip tried to install different versions but all the versions give this error.

- Python 8: it works

**Comment by darioamorosodaragona-tuni** [comment]
But after installed, i'm not able to load the module: 

```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[8], line 1
----> 1 from claspy.segmentation import BinaryClaSPSegmentation
      2 from claspy.data_loader import load_tssb_dataset
      3 #dataset, window_size, true_cps, time_series = load_tssb_dataset(names=("CricketX",)).iloc[0,:]


ModuleNotFoundError: No module named 'claspy'
```
If i try to launch 'pip install claspy', the package results already installed.

**Comment by ermshaua** [comment]
Python 3.11 is currently not supported, I'll have a look at 3.10 though. For now, if it's an option for you, try 3.9. This is the version I'm developing claspy with.

**Comment by darioamorosodaragona-tuni** [comment]
I'm trying to understand how to format the dataset to use Claspy. 
For now i'm just creating fake data with numpy: 

```
import numpy as np

# Set random seed for reproducibility
np.random.seed(0)

# Generate random time series data
num_points = 200  # Number of data points
mean1 = 0.0  # Mean of the first segment
mean2 = 5.0  # Mean of the second segment
std1 = 1.0  # Standard deviation of the first segment
std2 = 1.5  # Standard deviation of the second segment

# Generate data for the first segment
segment1 = np.random.normal(loc=mean1, scale=std1, size=num_points // 2)

# Generate data for the second segment
segment2 = np.random.normal(loc=mean2, scale=std2, size=num_points - num_points // 2)

# Concatenate the two segments
data = np.concatenate([segment1, segment2])
```

Then i try: 

```
clasp = BinaryClaSPSegmentation()
clasp.fit_predict(data)
clasp.plot(gt_cps=np.array([100]), heading="Segmentation of different umpire cricket signals", ts_name="ACC", file_path="segmentation_example.png")
```

But i got empty results: 

![image](https://github.com/ermshaua/claspy/assets/100281498/6332704e-105c-451c-83aa-51699156bbf6)

**Comment by ermshaua** [comment]
Try using the Euclidean distance using:

`clasp = BinaryClaSPSegmentation(distance="euclidean_distance").fit(time_series)`

More info on parameters are in [this notebook](https://github.com/ermshaua/claspy/blob/main/claspy/notebooks/clasp_configuration.ipynb).

**Comment by darioamorosodaragona-tuni** [comment]
The only to get a result is to use `acf` as window size. 

But why if a set the euclidean distance i get the "predict point" but not if i not set it?

`clasp = BinaryClaSPSegmentation(window_size="acf").fit(data)`

![output1](https://github.com/ermshaua/claspy/assets/100281498/711b075a-ed96-4a37-904b-2e8455b89269)

`clasp = BinaryClaSPSegmentation(window_size="acf", distance="euclidean_distance").fit(data)`

![output](https://github.com/ermshaua/claspy/assets/100281498/36fd4691-e330-4d85-aaa7-eef43fc110e6)

**Comment by ermshaua** [comment]
Sure, parameters often can be tuned. On default, ClaSP uses the normalized Euclidean distance, which only finds differences in shapes between segments, not in total values like in the time series you provided. In these cases, the normal Euclidean distance is a better choice.

**Comment by ermshaua** [comment]
@darioamorosodaragona-tuni I currently cannot reproduce your Python 3.10 error with claspy.

I use conda 4.9.2 and execute

```
conda create -n claspy-test python=3.10
conda activate claspy-test
pip install claspy
```

and it runs fine. Afterwards, I can successfully run the code from the readme in a Python interpreter. Do you get the same result if you do this?
